ASP_project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassLibrary1.BusinessLayer;
using ClassLibrary1.Model.Entities;

namespace ASP_project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Produit> listeProduit = Manager.Instance().GetTrendyProducts(5);
            Console.Write(listeProduit);
            return View(listeProduit);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASP_project/Controllers/ProduitsController.cs
using System.Web.Mvc;
using ClassLibrary1.BusinessLayer;
using ClassLibrary1.Model.Entities;
using System.Collections.Generic;

namespace ASP_project.Controllers
{
    public class ProduitsController : Controller
    {
        // GET: Produits

        public ActionResult Liste()
        {
            List<Produit> listeProduit = Manager.Instance().GetListeProduit();
            return View(listeProduit);
        }
        public ActionResult Details(int id)
        {
            Produit details = Manager.Instance().GetProduitById(id);
            return View(details);
        }
        public ActionResult Search(string filter)
        {
            List<Produit> produit = Manager.Instance().GetListeProduitByCode(filter);
            return View("Liste", produit);
        }

        public ActionResult AddProduits()
        {
            return View("FormProduit");
        }

        [HttpPost]
        public ActionResult AddProduits(Produit prod)
        {
            Produit produit = Manager.Instance().AddProduit(prod);
            return RedirectToAction("Liste");
        }

        public ActionResult ChangeProduits(int id)
        {
            Produit p = Manager.Instance().GetProduitById(id);
            return View("FormProduit", p);
        }

        [HttpPost]
        public ActionResult ChangeProduits(Produit prod)
        {
            //Produit p = Manager.Instance().EditProduit(id);
            return RedirectToAction("Liste");
        }
    }
}

ASP_project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ASP_project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASP_project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Fresh Delivery</h1>
</div>

<div class="row">
   
</div>
<div class="row">
    <h2>5 produits les plus vendus</h2>
    <table class="table">
        <thread>
            <tr>
                <td>Libélé</td>
            </tr>
        </thread>
        <tbody>
            @foreach (var produit in Model)
            {
                <tr>
                    <td><a href="@Url.Action("Details", "Produits", new {id=produit.IdProduit})">@produit.ProduitLibele</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

ASP_project/Views/Home/Orders.cshtml
@using ClassLibrary1.Model.Entities
@model List<Commande>
@{
    ViewBag.Title = "Orders";
}

<h2>5 dernières commandes</h2>
<table class="table">
    <thread>
        <tr>
            <td>Libélé</td>
        </tr>
    </thread>
    <tbody>
        @foreach (var commande in Model)
        {
            <tr>
                <td>@commande.IdCommande</td>
            </tr>
        }
    </tbody>
</table>

ASP_project/Views/Home/Products.cshtml
@using ClassLibrary1.Model.Entities
@model List<Produit>
@{
    ViewBag.Title = "Products";
}

<h2>5 produits les plus vendus</h2>
<table class="table">
    <thread>
        <tr>
            <td>Libélé</td>
        </tr>
    </thread>
    <tbody>
        @foreach (var produit in Model)
        {
            <tr>
                <td><a href="@Url.Action("Details", "Produits", new {id=produit.IdProduit})">@produit.ProduitLibele</a></td>
            </tr>
        }
    </tbody>
</table>

ASP_project/Views/Produits/Details.cshtml
@using ClassLibrary1.Model.Entities
@model Produit
@{
    ViewBag.Title = "Details produits";
}
<h2>Details</h2>

<html>

<body>
    <h2>Liste produits</h2>

    <table class="table">
        <thread>
            <tr>
                <td>Libélé</td>
                <td>Code</td>
                <td>Description</td>
                <td>Stock</td>
                <td>Categorie</td>

            </tr>
        </thread>
        <tbody>
                <tr>
                    <td>@Model.ProduitLibele</td>
                    <td>@Model.ProduitCode</td>
                    <td>@Model.ProduitDescription</td>
                    <td>@Model.ProduitStock</td>
                    <td>@Model.CategorieId</td>
                </tr>
        </tbody>
    </table>

</body>

</html>

ASP_project/Views/Produits/FormProduit.cshtml
@using ClassLibrary1.Model.Entities
@model Produit
@{
    ViewBag.Title = "FormProduit";
    string action = Model.IdProduit > 0 ? "ChangeProduits" : "AddProduits";
}

<h2>FormProduit</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm(action, "Produits", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {       
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.IdProduit)
                <h4>Créer un nouveau produit.</h4>
                <hr />
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitCode, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitCode, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitLibele, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitLibele, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitDescription, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitDescription, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitActif, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitActif, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitStock, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitStock, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ProduitPrix, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.ProduitPrix, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.CategorieId, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(p => p.CategorieId, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default" value="Ajouter le produit" />
                    </div>
                </div>
            }
        </section>

ASP_project/Views/Produits/Liste.cshtml
@using ClassLibrary1.Model.Entities
@model List<Produit>
@{
    ViewBag.Title = "Liste";
}
    <h2>Liste produits</h2>
    <form class="navbar-form navbar-left" role="search" action="@Url.Action("Search", "Produits")" method="get">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" name="filter">
        </div>
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>Libélé</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var produit in Model)
            {
                <tr>
                    <td><a href="@Url.Action("Details", "Produits", new {id=produit.IdProduit})">@produit.ProduitLibele</a></td>
                    <td><a href="@Url.Action("ChangeProduits", "Produits", new { id = produit.IdProduit })" class="btn">Modifier un produit</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="@Url.Action("AddProduits", "Produits")" class="btn">Ajouter un produit</a>

ASP_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>